### ISSUE TITLE
Permissions dont Load.

### ISSUE THREAD

**Issue by Cl4udia** [vincidev/BungeeBan#11]
Hello,
Im from Germany, so im sorry for my bad englisch.

Im an Admin from my Minecraft Server Network, and i use BungeePerms for my Bungeecord Permissions.
I have connected with my Mysql Bank...
But when i create a new group and give them permissions, the Player who has th group dont has the permissions.
The only thing what works are the '*' Permissions.
Could you please tell my why is it so?

Thank you

**Comment by vincidev** [comment]
Sadly, I can't help you on this as it might be a problem with the permissions plugin.
