### ISSUE TITLE
Bug with UUID support

### ISSUE THREAD

**Issue by NyCoSD** [vincidev/BungeeBan#12]
Hello  @vincidev,

Your plugin 'BungeeBan' indicated :[http://puu.sh/oN7lO/146ca67cea.png](url) A problem on my side ?
I test with eu or us api it's equal 

Thank you in advance

**Comment by NyCoSD** [comment]
You are a solution please ?

**Comment by vincidev** [comment]
Update will come today.

**Comment by NyCoSD** [comment]
Ok thank you

**Comment by NyCoSD** [comment]
Update Soon ? ( Sorry for recontact you, it's very important my server turn with :/ )
