### ISSUE TITLE
Permissions dont Load.

### ISSUE THREAD

**Issue by Cl4udia** [vincidev/BungeeBan#16]
Hello,
I have BungeeBan and PermissionsEX connected to an MYSQL Database.
But when i add a Player or a group the permission zb. BungeeBan.Ban
they dont get the permission!
Please help me :C

**Comment by vincidev** [comment]
How about reading the wiki? https://github.com/vincidev/BungeeBan/wiki/Permissions

**Comment by Cl4udia** [comment]
It doesnt work:
http://pastebin.com/93ZwTufK
Please help me

2016-05-27 13:04 GMT+02:00 Luca Vinciguerra <notifications@github.com>:

**Comment by ImNatho** [comment]
You didn't add the perms to the admin group?

**Comment by Cl4udia** [comment]
Noo, Admin group has * Permissions, but the users who are in the team group
cant ban or kick somebody


2016-05-29 10:41 GMT+02:00 Natho <notifications@github.com>:

**Comment by Cl4udia** [comment]
Please help me, i need you now.


2016-05-29 17:01 GMT+02:00 Hacker Reports Claudex <
jannicmaigler109@gmail.com>:

**Comment by ImNatho** [comment]
Does the '*' permission even work on bungee? Try assigning every permission you need for BungeeBan to the admin group.

**Comment by Cl4udia** [comment]
Could we please meet us on an teamspeak server or sepaking in Skype?

2016-06-06 1:20 GMT+02:00 Natho <notifications@github.com>:

**Comment by ImNatho** [comment]
Can you please just add the permissions you want to use as admin to the admin group...
@vincidev please lock this.

**Comment by Cl4udia** [comment]
Ah du bist doch deutscher :D
Dann können wir ja TS oder Skype..

2016-06-07 5:58 GMT+02:00 Natho <notifications@github.com>:

**Comment by Cl4udia** [comment]
Ich habe noch ein weiteres Problem..
Das ganze Plugin funktioniert bei mir  nicht mehr!
Ich hatte den BungeeBan ORdner noch gespeichert aber die .jar Datei
gelöscht..
Und jetzt wo ich die -jar Datei wieder hochladen will, funktioniert das
Plugin nicht mehr...
Ich würde Sie wirklich bitten mit mir näher in Kontakt zu kommen, da dies
ein wirklich großes Problem darstellt.

Skype: jannicm1
Ts3-Server: TroubleMC.net

2016-06-08 12:59 GMT+02:00 Hacker Reports Claudex <
jannicmaigler109@gmail.com>:

**Comment by ImNatho** [comment]
Die Admin- Konzern nicht als Standard alle Rechte

**Comment by Cl4udia** [comment]
Häh?
Bitte TS oder Skype!!

2016-06-08 14:40 GMT+02:00 Natho <notifications@github.com>:
