### ISSUE TITLE
No bans, Kicks, mutes people

### ISSUE THREAD

**Issue by iTzMiguelFX** [vincidev/BungeeBan#2]
I like this plugin but have I problem
No**_ bans, Kicks, mutes people_**
And I wanted to know if we can fix it

**Comment by vincidev** [comment]
Are you running a cracked server?

**Comment by vincidev** [comment]
I fixed this now. See [https://github.com/vincidev/BungeeBan/issues/3](https://github.com/vincidev/BungeeBan/issues/3)
