### ISSUE TITLE
UUID not found

### ISSUE THREAD

**Issue by equalsIgnoreCase** [vincidev/BungeeBan#3]
When i try to ban oder mute a player, the plugin do not find the uuid. version 1.9, version of your plugin is the newest. I reinstalled the plugin also, but it doesnt work.

**Comment by xXAndrew28Xx** [comment]
+1, This is becoming a serious issue for my network.

**Comment by xXAndrew28Xx** [comment]
https://github.com/vincidev/BungeeBan/blob/master/src/de/vincidev/bungeeban/util/PlayerUtil.java#L17
Related to this line, the API does not work atm.

**Comment by xXAndrew28Xx** [comment]
#4

**Comment by xXAndrew28Xx** [comment]
Apparently org.json is part of the jar too. Surprised you guys aren't using maven shading but here is the jar where I changed the API to use US which actually worked and included in the org.json 
https://www.dropbox.com/s/tbvxpu1kvldgegw/BungeeBan.jar?dl=0

**Comment by vincidev** [comment]
I might do a setting where you can select wether you want to use the us or eu api. that would make sense I guess

**Comment by vincidev** [comment]
I fixed this now. The eu api seems to be down for now but untill it is back up you can select the us api in the config. Hope it helped!
