### ISSUE TITLE
No Perms And I'm Opped And Have The Perms In My Group

### ISSUE THREAD

**Issue by HyperClawz** [vincidev/BungeeBan#5]
No Perms And I'm Opped And Have The Perms In My Group Help!!

**Comment by vincidev** [comment]
You didnt read the wiki.... Being able to read is an advantage my friend ^^. [https://github.com/vincidev/BungeeBan/wiki/Permissions](https://github.com/vincidev/BungeeBan/wiki/Permissions) (Disclaimer)
