### ISSUE TITLE
Are they a bug with uuid ? 

### ISSUE THREAD

**Issue by HoliShyt** [vincidev/BungeeBan#6]
Hello,
 i think there is a bug in your plugins :/ In fact, i can't ban or mute person :/ " uuid of player coul'd not be foud ..." Did there is a patch for this ? i also haven't got link the MySQL but i don't thing thaht is the raison for this error
Thx ( Sorry for the gramatical errors i'm french :3 )

**Comment by vincidev** [comment]
Fixed now. See [https://github.com/vincidev/BungeeBan/issues/3](https://github.com/vincidev/BungeeBan/issues/3)

**Comment by HoliShyt** [comment]
Thx ;)

2016-05-02 14:22 GMT+02:00 Luca Vinciguerra <notifications@github.com>:
