### ISSUE TITLE
Issue with banning.

### ISSUE THREAD

**Issue by Zeddart** [vincidev/BungeeBan#9]
Hello! Iv'e recently started using this plugin and i am having problems with banning players!

The issue is that everytime i try to create a ban the plugins responds with "The UUID of this player could not be found." I have checked around the config and the connections to my MySQL database and everything should be working. So what am i doing wrong or is it a bug?

As stated i am using MySQL.

![ban](https://cloud.githubusercontent.com/assets/13826584/15081886/466f4990-13c5-11e6-9cb7-f952243c67ab.png)

**Comment by vincidev** [comment]
Try switching the api from 'us' to 'eu'

**Comment by Zeddart** [comment]
Sorry, what API?

**Comment by Zeddart** [comment]
Can't find anywhere how to switch from US to EU
